# Netlify Configuration for Landing Pages Automation

[build]
  # Build command - install deps at root first, then build
  command = "cd ../.. && npm install && npm run build"

  # Publish directory - Next.js build output
  publish = ".next"

  # Functions directory
  functions = "netlify/functions"

  # Base directory - root of Next.js app
  base = "apps/frontend"

[build.environment]
  # Node version
  NODE_VERSION = "20"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings
[functions]
  # Node.js version for functions
  node_bundler = "esbuild"

  # External node modules (don't bundle)
  external_node_modules = ["@anthropic-ai/sdk"]

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"

# Environment-specific settings
[context.production]
  command = "cd ../.. && npm install && npm run build"

[context.deploy-preview]
  command = "cd ../.. && npm install && npm run build"

[context.branch-deploy]
  command = "cd ../.. && npm install && npm run build"
