# Netlify Configuration - placed in Next.js app root for auto-detection

[build]
  base = "apps/frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings
[functions]
  directory = "apps/frontend/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk"]
