# Netlify Configuration for Landing Pages Automation

[build]
  # Build command
  command = "npm install && npm run build"

  # Publish directory - Next.js build output (relative to root)
  publish = "apps/frontend/.next"

  # Functions directory (relative to root)
  functions = "apps/frontend/netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "20"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings
[functions]
  # Node.js version for functions
  node_bundler = "esbuild"

  # External node modules (don't bundle)
  external_node_modules = ["@anthropic-ai/sdk"]

  # Directory for functions (must match above)
  directory = "apps/frontend/netlify/functions"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
